config/routes.rb
Rails.application.routes.draw do
  root to: 'target_gems#index'

  resources :target_gems
end

app/models/target_gem.rb
# == Schema Information
#
# Table name: target_gems
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class TargetGem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/target_gems_controller.rb
class TargetGemsController < ApplicationController
  inherit_resources
  actions :all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.slim
div role="navigation" class="navbar navbar-inverse navbar-fixed-top"
  .container
    .navbar-header
      a href="#" class="navbar-brand" Gems Stats

    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#" All

      .navbar-form.navbar-left
        = link_to new_target_gem_path, class: 'btn btn-primary' do
          i.fa.fa-plus.fa-fw
          span Add gem

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gems Stats
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header= render 'header'


    article.container
      = yield

app/views/target_gems/new.slim
= simple_form_for @target_gem do |f|
  = f.input :name
  = f.submit class: 'btn btn-primary'